/* ================================================================
   NEXUS — Routines Module
   Rotinas recorrentes com geração automática de tarefas.
   ================================================================ */

import { requireAuth } from '/services/auth.service.js';
import { db } from '/services/firebase-config.js';
import {
    collection, doc, query, where, orderBy, getDocs, addDoc,
    updateDoc, deleteDoc, serverTimestamp, Timestamp, getDoc
} from 'firebase/firestore';
import { renderSidebar } from '/components/sidebar.js';
import { renderHeader } from '/components/header.js';
import { createModal, openModal, closeModal, confirmDialog } from '/components/modal.js';
import { toast } from '/components/toast.js';
import { sanitizeText } from '/utils/sanitizer.js';
import { formatDate, calcNextDue, shouldGenerateRoutine, todayString } from '/utils/date-utils.js';
import {
    escapeHtml, getInitials, stringToColor, uid as genUid,
    getStoredTheme, setTheme, canPerformAction, FREQUENCY_LABELS, DAY_NAMES
} from '/utils/helpers.js';
import { buildGutObject, renderGutBadge } from '/utils/gut-calculator.js';
import { logAudit, AUDIT_ACTIONS } from '/services/audit.service.js';

let _profile = null;
let _routines = [];
let _allUsers = [];
let _editingId = null;

// ================================================================
// INIT
// ================================================================
async function init() {
    setTheme(getStoredTheme());

    _profile = await requireAuth('viewer');
    if (!_profile) return;

    renderSidebar('routines', _profile);
    renderHeader(_profile, 'Rotinas', 'Tarefas recorrentes automáticas');

    document.getElementById('page-content').innerHTML = buildLayout();

    await Promise.all([loadUsers(), loadRoutines()]);
    await autoGenerateDueTasks();
    renderRoutines();
    setupListeners();
    createRoutineModal();
    maybeOpenCreateRoutineFromQuery();

    document.getElementById('app-loading').style.display = 'none';
    document.getElementById('app').style.display = 'flex';
    window.renderIcons?.();
}

// ================================================================
// LAYOUT
// ================================================================
function buildLayout() {
    const canEdit = canPerformAction(_profile, 'edit_task');
    return `
    <div class="page-header">
      <div class="page-header-left">
        <h2>Rotinas</h2>
        <p>Gerenciamento de tarefas recorrentes</p>
      </div>
      <div class="page-header-actions">
        ${canEdit ? `<button class="btn btn-primary" onclick="window._openCreateRoutine()">
          <i data-fa-icon="plus"></i> Nova Rotina
        </button>` : ''}
      </div>
    </div>

    <!-- Tabs: Ativas / Inativas -->
    <div class="filter-tabs" id="routine-tabs">
      <button class="filter-tab active" data-filter="active">Ativas</button>
      <button class="filter-tab" data-filter="inactive">Inativas</button>
      <button class="filter-tab" data-filter="all">Todas</button>
    </div>

    <!-- Info banner -->
    <div class="alert alert-info mb-4" style="border-radius:10px;padding:12px 16px;display:flex;align-items:flex-start;gap:10px;background:var(--color-info-light);border:1px solid var(--color-info-border)">
      <i data-fa-icon="info" style="width:16px;height:16px;color:var(--color-info);margin-top:1px;flex-shrink:0"></i>
      <span style="font-size:13px;color:var(--text-secondary)">
        As rotinas geram tarefas automaticamente no Kanban quando estão vencidas. A verificação ocorre ao abrir esta página.
      </span>
    </div>

    <!-- List -->
    <div id="routines-container">
      <div class="page-loader"><div class="spinner"></div></div>
    </div>`;
}

function setupListeners() {
    document.getElementById('routine-tabs')?.addEventListener('click', e => {
        const btn = e.target.closest('[data-filter]');
        if (!btn) return;
        document.querySelectorAll('#routine-tabs .filter-tab').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        renderRoutines(btn.dataset.filter);
    });
}

function maybeOpenCreateRoutineFromQuery() {
    const params = new URLSearchParams(window.location.search);
    if (params.get('create') !== '1') return;
    if (!canPerformAction(_profile, 'edit_task')) return;
    window._openCreateRoutine();
}

// ================================================================
// CARREGAR DADOS
// ================================================================
async function loadUsers() {
    try {
        const snap = await getDocs(collection(db, 'users'));
        const usersById = new Map();

        snap.docs.forEach((d) => {
            const data = d.data() || {};
            const id = data.uid || d.id;
            const email = String(data.email || '').trim().toLowerCase();
            const fallbackName = email ? email.split('@')[0] : '';
            const name = String(data.name || data.displayName || data.fullName || fallbackName).trim();

            if (data.active === false) return;
            if (!name && !email) return;

            usersById.set(id, {
                id,
                name: name || email,
                email,
                active: true,
            });
        });

        if (_profile?.uid && !usersById.has(_profile.uid)) {
            usersById.set(_profile.uid, {
                id: _profile.uid,
                name: _profile.name || _profile.email || 'Você',
                email: (_profile.email || '').toLowerCase(),
                active: true,
            });
        }

        _allUsers = Array.from(usersById.values())
            .sort((a, b) => (a.name || a.email || '').localeCompare(b.name || b.email || '', 'pt-BR'));
    } catch (e) {
        _allUsers = _profile?.uid ? [{
            id: _profile.uid,
            name: _profile.name || _profile.email || 'Você',
            email: (_profile.email || '').toLowerCase(),
            active: true,
        }] : [];
    }
}

async function loadRoutines() {
    try {
        const snap = await getDocs(query(collection(db, 'routines'), orderBy('createdAt', 'desc')));
        _routines = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    } catch (e) {
        console.error('[Routines] Load error:', e);
        _routines = [];
    }
}

// ================================================================
// AUTO-GERAR TAREFAS VENCIDAS
// ================================================================
async function autoGenerateDueTasks() {
    const active = _routines.filter(r => r.active !== false);
    let generated = 0;
    for (const routine of active) {
        if (!shouldGenerateRoutine(routine)) continue;
        try {
            // Verificar se já foi gerada hoje para esta rotina
            const today = todayString();
            const existing = await getDocs(query(
                collection(db, 'tasks'),
                where('routineId', '==', routine.id),
                where('routineDate', '==', today)
            ));
            if (!existing.empty) continue;

            const nextDue = calcNextDue(routine.frequency, routine.specificDays);
            await addDoc(collection(db, 'tasks'), {
                title: routine.title,
                board: 'routines',
                status: 'todo',
                assigneeId: routine.assigneeId || '',
                assigneeName: routine.assigneeName || '',
                objective: routine.objective || '',
                description: routine.description || '',
                additionalInfo: '',
                gut: routine.gut || { gravity: 1, urgency: 1, trend: 1, score: 1 },
                checklist: routine.checklist || [],
                parentTaskId: null,
                routineId: routine.id,
                routineDate: today,
                dueDate: null,
                createdBy: 'system',
                requesterId: 'system',
                requesterName: 'Sistema (Rotina)',
                createdAt: serverTimestamp(),
                updatedAt: serverTimestamp(),
            });

            // Atualiza lastGenerated e nextDue
            await updateDoc(doc(db, 'routines', routine.id), {
                lastGenerated: serverTimestamp(),
                nextDue: nextDue ? Timestamp.fromDate(nextDue) : null,
                updatedAt: serverTimestamp(),
            });
            generated++;
        } catch (e) {
            console.error('[Routines] Auto-generate error for', routine.id, e);
        }
    }
    if (generated > 0) {
        toast.info('Rotinas', `${generated} tarefa(s) gerada(s) automaticamente.`);
        await loadRoutines(); // recarregar após geração
    }
}

// ================================================================
// RENDER
// ================================================================
function renderRoutines(filter = 'active') {
    const container = document.getElementById('routines-container');
    if (!container) return;

    let filtered = _routines;
    if (filter === 'active') filtered = _routines.filter(r => r.active !== false);
    if (filter === 'inactive') filtered = _routines.filter(r => r.active === false);

    if (filtered.length === 0) {
        container.innerHTML = `
      <div class="empty-state">
        <div class="empty-state-icon"><i data-fa-icon="repeat"></i></div>
        <h3>Nenhuma rotina encontrada</h3>
        <p>Crie rotinas para automatizar tarefas recorrentes.</p>
        ${canPerformAction(_profile, 'edit_task') ? `<button class="btn btn-primary" onclick="window._openCreateRoutine()">
          <i data-fa-icon="plus"></i> Nova Rotina
        </button>` : ''}
      </div>`;
        window.renderIcons?.();
        return;
    }

    container.innerHTML = `
    <div class="table-wrapper">
      <table class="table">
        <thead>
          <tr>
            <th>Rotina</th>
            <th>Frequência</th>
            <th>Responsável</th>
            <th>Prioridade</th>
            <th>Próxima Geração</th>
            <th>Status</th>
            <th style="width:80px"></th>
          </tr>
        </thead>
        <tbody id="routines-tbody">
          ${filtered.map(r => buildRoutineRow(r)).join('')}
        </tbody>
      </table>
    </div>`;
    window.renderIcons?.();
}

function buildRoutineRow(r) {
    const next = r.nextDue ? formatDate(r.nextDue, 'short') : '—';
    const gutBadge = renderGutBadge(r.gut);
    const freqLabel = FREQUENCY_LABELS[r.frequency] || r.frequency || '—';
    const daysLabel = r.frequency === 'specific_days' && r.specificDays?.length
        ? ` (${r.specificDays.map(d => DAY_NAMES[d]).join(', ')})`
        : '';
    const active = r.active !== false;
    const canEdit = canPerformAction(_profile, 'edit_task');

    return `
    <tr data-id="${r.id}">
      <td>
        <div style="font-weight:600;color:var(--text-primary)">${escapeHtml(r.title)}</div>
        ${r.objective ? `<div style="font-size:11px;color:var(--text-muted)">${escapeHtml(r.objective)}</div>` : ''}
      </td>
      <td style="font-size:13px">${freqLabel}${daysLabel}</td>
      <td>
        ${r.assigneeName ? `
          <div style="display:flex;align-items:center;gap:8px">
            <div class="assignee-avatar-sm" style="background:${stringToColor(r.assigneeName)}">${getInitials(r.assigneeName)}</div>
            <span style="font-size:13px">${escapeHtml(r.assigneeName)}</span>
          </div>` : '<span style="color:var(--text-muted)">—</span>'}
      </td>
      <td>${gutBadge}</td>
      <td style="font-size:13px">${next}</td>
      <td>
        <span class="status-chip ${active ? 'status-in_progress' : 'status-cancelled'}">
          <span class="status-dot"></span>${active ? 'Ativa' : 'Inativa'}
        </span>
      </td>
      <td>
        ${canEdit ? `
          <div style="display:flex;gap:4px">
            <button class="btn btn-ghost btn-xs" title="Editar" onclick="window._editRoutine('${r.id}')">
              <i data-fa-icon="edit-2" style="width:13px;height:13px"></i>
            </button>
            <button class="btn btn-ghost btn-xs danger" title="${active ? 'Desativar' : 'Ativar'}"
                    onclick="window._toggleRoutine('${r.id}', ${active})">
              <i data-fa-icon="${active ? 'pause-circle' : 'play-circle'}" style="width:13px;height:13px"></i>
            </button>
          </div>` : ''}
      </td>
    </tr>`;
}

// ================================================================
// CRIAR / EDITAR MODAL
// ================================================================
function createRoutineModal() {
    const gutOpts = [1, 2, 3, 4, 5].map(n => `<option value="${n}">${n}</option>`).join('');
    const daysEl = DAY_NAMES.map((d, i) => `
    <label style="display:flex;align-items:center;gap:6px;font-size:12px;cursor:pointer">
      <input type="checkbox" class="form-checkbox" name="specific-day" value="${i}"> ${d}
    </label>`).join('');

    createModal({
        id: 'modal-routine',
        title: 'Nova Rotina',
        size: 'md',
        body: `
      <form id="form-routine" class="form-grid" novalidate>
        <div class="form-group form-col-full">
          <label class="form-label">Título *</label>
          <input type="text" id="routine-title" class="form-input" maxlength="200" required>
        </div>
        <div class="form-group form-col-full">
          <label class="form-label">Objetivo</label>
          <input type="text" id="routine-objective" class="form-input" maxlength="200">
        </div>
        <div class="form-group form-col-full">
          <label class="form-label">Descrição</label>
          <textarea id="routine-description" class="form-textarea" rows="2"></textarea>
        </div>
        <div class="form-group">
          <label class="form-label">Responsável</label>
          <input type="hidden" id="routine-assignee" value="">
          <div id="routine-assignee-container" class="involved-container" onclick="window._openAssigneePicker()">
            <span class="involved-placeholder">Clique para selecionar responsável...</span>
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">Frequência *</label>
          <select id="routine-frequency" class="form-select" onchange="window._onFreqChange()">
            ${Object.entries(FREQUENCY_LABELS).map(([k, v]) => `<option value="${k}">${v}</option>`).join('')}
          </select>
        </div>
        <div id="specific-days-wrapper" class="form-group form-col-full" style="display:none">
          <label class="form-label">Dias da semana</label>
          <div style="display:flex;flex-wrap:wrap;gap:12px">${daysEl}</div>
        </div>
        <div class="form-group form-col-full">
          <label class="form-label" style="margin-bottom:8px">
            Matriz GUT <span class="badge badge-gray" id="routine-gut-preview">Score: —</span>
          </label>
          <div class="gut-grid">
            <div class="gut-item"><label>G</label><select id="routine-gut-g" class="form-select form-select-sm">${gutOpts}</select></div>
            <div class="gut-item"><label>U</label><select id="routine-gut-u" class="form-select form-select-sm">${gutOpts}</select></div>
            <div class="gut-item"><label>T</label><select id="routine-gut-t" class="form-select form-select-sm">${gutOpts}</select></div>
          </div>
        </div>
      </form>`,
        footer: `
      <button class="btn btn-secondary" onclick="closeModal('modal-routine')">Cancelar</button>
      <button class="btn btn-primary" id="btn-save-routine" onclick="window._saveRoutine()">
        <i data-fa-icon="save"></i> Salvar
      </button>`,
    });

    ['routine-gut-g', 'routine-gut-u', 'routine-gut-t'].forEach(id => {
        document.getElementById(id)?.addEventListener('change', () => {
            const g = parseInt(document.getElementById('routine-gut-g')?.value || 1);
            const u = parseInt(document.getElementById('routine-gut-u')?.value || 1);
            const t = parseInt(document.getElementById('routine-gut-t')?.value || 1);
            const { calcGutScore } = window; // fallback
            const score = g * u * t;
            const el = document.getElementById('routine-gut-preview');
            if (el) el.textContent = `Score: ${score}`;
        });
    });
}

window._onFreqChange = function () {
    const freq = document.getElementById('routine-frequency')?.value;
    const wrapper = document.getElementById('specific-days-wrapper');
    if (wrapper) wrapper.style.display = freq === 'specific_days' ? 'block' : 'none';
};

window._openCreateRoutine = function () {
    if (!canPerformAction(_profile, 'edit_task')) {
        toast.warning('Sem permissão', 'Você precisa ser editor ou admin.');
        return;
    }
    if (!document.getElementById('modal-routine')) createRoutineModal();
    _editingId = null;
    document.getElementById('form-routine')?.reset();
    document.getElementById('specific-days-wrapper').style.display = 'none';
    const titleEl = document.querySelector('#modal-routine .modal-title');
    if (titleEl) titleEl.textContent = 'Nova Rotina';
    openModal('modal-routine');
    window.renderIcons?.();
};
// Ensure modal exists before any DOM access
if (!document.getElementById('modal-routine')) createRoutineModal();

window._editRoutine = function (id) {
    const routine = _routines.find(r => r.id === id);
    if (!routine) return;
    _editingId = id;

    setTimeout(() => {
        document.getElementById('routine-title').value = routine.title || '';
        document.getElementById('routine-objective').value = routine.objective || '';
        document.getElementById('routine-description').value = routine.description || '';
        document.getElementById('routine-frequency').value = routine.frequency || 'daily';
        document.getElementById('routine-gut-g').value = routine.gut?.gravity || 1;
        document.getElementById('routine-gut-u').value = routine.gut?.urgency || 1;
        document.getElementById('routine-gut-t').value = routine.gut?.trend || 1;

        const assigneeEl = document.getElementById('routine-assignee');
        if (assigneeEl && routine.assigneeId) {
            assigneeEl.value = routine.assigneeId;
            renderAssigneeContainer(routine.assigneeId, routine.assigneeName || '');
        }

        // Specific days
        document.querySelectorAll('[name="specific-day"]').forEach(cb => {
            cb.checked = (routine.specificDays || []).includes(parseInt(cb.value));
        });
        window._onFreqChange();

        document.querySelector('#modal-routine .modal-title').textContent = 'Editar Rotina';
    }, 50);

    openModal('modal-routine');
    window.renderIcons?.();
};

window._toggleRoutine = async function (id, currentlyActive) {
    const action = currentlyActive ? 'desativar' : 'ativar';
    const confirmed = await confirmDialog(
        `${currentlyActive ? 'Desativar' : 'Ativar'} Rotina`,
        `Deseja ${action} esta rotina?`,
        currentlyActive ? 'Desativar' : 'Ativar',
        currentlyActive
    );
    if (!confirmed) return;
    try {
        await updateDoc(doc(db, 'routines', id), {
            active: !currentlyActive,
            updatedAt: serverTimestamp()
        });
        toast.success('Atualizado', `Rotina ${!currentlyActive ? 'ativada' : 'desativada'}.`);
        await loadRoutines();
        renderRoutines();
    } catch (e) {
        toast.error('Erro', 'Não foi possível atualizar a rotina.');
    }
};

// ================================================================
// SALVAR ROTINA
// ================================================================
window._saveRoutine = async function () {
    const title = sanitizeText(document.getElementById('routine-title')?.value?.trim() || '');
    const objective = sanitizeText(document.getElementById('routine-objective')?.value?.trim() || '');
    const description = sanitizeText(document.getElementById('routine-description')?.value?.trim() || '');
    const frequency = document.getElementById('routine-frequency')?.value || 'daily';
    const assigneeId = document.getElementById('routine-assignee')?.value || '';
    const assigneeName = getUserName(assigneeId);
    const g = parseInt(document.getElementById('routine-gut-g')?.value || 1);
    const u = parseInt(document.getElementById('routine-gut-u')?.value || 1);
    const t = parseInt(document.getElementById('routine-gut-t')?.value || 1);

    const specificDays = frequency === 'specific_days'
        ? Array.from(document.querySelectorAll('[name="specific-day"]:checked')).map(cb => parseInt(cb.value))
        : [];

    if (!title) { toast.warning('Campo obrigatório', 'Informe o título da rotina.'); return; }
    if (frequency === 'specific_days' && specificDays.length === 0) {
        toast.warning('Selecione os dias', 'Escolha pelo menos um dia da semana.'); return;
    }

    const gut = buildGutObject(g, u, t);
    const nextDue = calcNextDue(frequency, specificDays);
    const payload = {
        title, objective, description, frequency, specificDays, gut,
        assigneeId, assigneeName, active: true,
        nextDue: nextDue ? Timestamp.fromDate(nextDue) : null,
        updatedAt: serverTimestamp(),
    };

    const btn = document.getElementById('btn-save-routine');
    if (btn) btn.disabled = true;

    try {
        if (_editingId) {
            await updateDoc(doc(db, 'routines', _editingId), payload);
            toast.success('Atualizado', 'Rotina atualizada.');
        } else {
            const ndoc = await addDoc(collection(db, 'routines'), {
                ...payload, createdBy: _profile.uid, lastGenerated: null, createdAt: serverTimestamp()
            });
            await logAudit(AUDIT_ACTIONS.ROUTINE_CREATED, ndoc.id, 'routine', { title });
            toast.success('Criado', 'Rotina criada com sucesso.');
        }
        closeModal('modal-routine');
        await loadRoutines();
        renderRoutines();
    } catch (e) {
        console.error('[Routines] Save error:', e);
        toast.error('Erro', 'Não foi possível salvar a rotina.');
    } finally {
        if (btn) btn.disabled = false;
    }
};

init().catch(e => { console.error(e); toast.error('Erro', 'Falha ao carregar módulo de rotinas.'); });

// ================================================================
// ASSIGNEE PICKER
// ================================================================
function getUserName(userId) {
    const user = _allUsers.find(u => u.id === userId);
    return user ? user.name : '';
}

window._openAssigneePicker = function() {
    createModal({
        id: 'modal-assignee',
        title: 'Selecionar Responsável',
        size: 'sm',
        body: `
            <div style="max-height:400px;overflow-y:auto">
                <div class="search-box mb-3">
                    <i data-fa-icon="search" class="search-icon"></i>
                    <input type="text" id="search-assignee" class="search-input" placeholder="Buscar..." oninput="window._filterAssigneePicker()">
                </div>
                <div id="assignee-picker-list">${buildAssigneePickerList(_allUsers)}</div>
            </div>`,
        footer: `<button class="btn btn-primary" onclick="closeModal('modal-assignee')">Concluído</button>`,
    });
    
    openModal('modal-assignee');
    window.renderIcons?.();
};

function buildAssigneePickerList(users) {
    const selectedId = document.getElementById('routine-assignee')?.value || '';
    return users.map(u => `
        <div class="involved-picker-item${selectedId === u.id ? ' selected' : ''}" data-id="${u.id}" data-name="${escapeHtml(u.name)}" onclick="window._selectAssignee('${u.id}', '${escapeHtml(u.name).replace(/'/g, "\\'")}')">
            <div class="involved-avatar" style="background:${stringToColor(u.name)}">${getInitials(u.name)}</div>
            <div class="involved-info">
                <div class="involved-name">${escapeHtml(u.name)}</div>
                <div class="involved-email">${escapeHtml(u.email)}</div>
            </div>
            <i data-fa-icon="check" class="check-icon"></i>
        </div>
    `).join('');
}

window._selectAssignee = function(userId, userName) {
    document.getElementById('routine-assignee').value = userId;
    renderAssigneeContainer(userId, userName);
    document.querySelectorAll('#assignee-picker-list .involved-picker-item').forEach(el => {
        el.classList.toggle('selected', el.dataset.id === userId);
    });
};

function renderAssigneeContainer(userId, userName) {
    const container = document.getElementById('routine-assignee-container');
    if (!container) return;
    
    if (!userId) {
        container.innerHTML = '<span class="involved-placeholder">Clique para selecionar responsável...</span>';
        window.renderIcons?.();
        return;
    }
    
    container.innerHTML = `
        <div class="involved-chip" data-id="${userId}">
            <div class="involved-avatar" style="background:${stringToColor(userName)}">${getInitials(userName)}</div>
            <span>${escapeHtml(userName)}</span>
            <i data-fa-icon="x" onclick="window._removeAssignee(event)"></i>
        </div>`;
    container.innerHTML += '<span class="involved-add-btn">+ Alterar</span>';
    window.renderIcons?.();
}

window._removeAssignee = function(event) {
    event.stopPropagation();
    document.getElementById('routine-assignee').value = '';
    renderAssigneeContainer('', '');
};

window._filterAssigneePicker = function() {
    const search = document.getElementById('search-assignee')?.value?.toLowerCase() || '';
    const filtered = _allUsers.filter(u => 
        (u.name || '').toLowerCase().includes(search) || 
        (u.email || '').toLowerCase().includes(search)
    );
    document.getElementById('assignee-picker-list').innerHTML = buildAssigneePickerList(filtered);
    window.renderIcons?.();
};
